# Generated by Django 4.2.13 on 2025-07-12 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template_id",
                    models.CharField(default="template_2_1", max_length=50),
                ),
                (
                    "frame_style",
                    models.CharField(
                        choices=[
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                            ("minimal", "Minimal"),
                            ("vintage", "Vintage"),
                        ],
                        default="modern",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="ImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="collages/%Y/%m/%d/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("x_position", models.FloatField(default=0)),
                ("y_position", models.FloatField(default=0)),
                ("width", models.FloatField(default=200)),
                ("height", models.FloatField(default=200)),
                (
                    "collage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="collages.collage",
                    ),
                ),
            ],
            options={"ordering": ["order"],},
        ),
    ]
